//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_nhap_hang
    {
        public string id_hoa_don_nhap { get; set; }
        public int id_muc { get; set; }
        public string id_xe { get; set; }
        public decimal gia_nhap { get; set; }
        public byte so_luong { get; set; }
        public decimal chiet_khau { get; set; }
    
        public virtual don_nhap_hang don_nhap_hang { get; set; }
        public virtual xe xe { get; set; }
    }
}
