//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class don_nhap_hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public don_nhap_hang()
        {
            this.chi_tiet_nhap_hang = new HashSet<chi_tiet_nhap_hang>();
        }
    
        public int stt { get; set; }
        public string id_hoa_don_nhap { get; set; }
        public string id_nsx { get; set; }
        public string id_chu_kho { get; set; }
        public System.DateTime ngay_nhap_hang { get; set; }
        public string id_cua_hang { get; set; }
        public decimal tong_tien { get; set; }
    
        public virtual cua_hang cua_hang { get; set; }
        public virtual nhan_viens nhan_viens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_nhap_hang> chi_tiet_nhap_hang { get; set; }
        public virtual nsx nsx { get; set; }
    }
}
