//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class kho
    {
        public string id_cua_hang { get; set; }
        public string id_xe { get; set; }
        public short so_luong_khong_loi { get; set; }
        public byte so_luong_bi_loi { get; set; }
    
        public virtual cua_hang cua_hang { get; set; }
        public virtual xe xe { get; set; }
    }
}
