//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BikeStoreShoppingEntities : DbContext
    {
        public BikeStoreShoppingEntities()
            : base("name=BikeStoreShoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chi_tiet_don_dat_hang> chi_tiet_don_dat_hang { get; set; }
        public virtual DbSet<cua_hang> cua_hang { get; set; }
        public virtual DbSet<dat_hang> dat_hang { get; set; }
        public virtual DbSet<khach_hang> khach_hang { get; set; }
        public virtual DbSet<chuc_vu> chuc_vu { get; set; }
        public virtual DbSet<nhan_viens> nhan_viens { get; set; }
        public virtual DbSet<chi_tiet_nhap_hang> chi_tiet_nhap_hang { get; set; }
        public virtual DbSet<don_nhap_hang> don_nhap_hang { get; set; }
        public virtual DbSet<nsx> nsxes { get; set; }
        public virtual DbSet<hang_xe> hang_xe { get; set; }
        public virtual DbSet<kho> khoes { get; set; }
        public virtual DbSet<loai_xe> loai_xe { get; set; }
        public virtual DbSet<xe> xes { get; set; }
    }
}
