//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public xe()
        {
            this.chi_tiet_don_dat_hang = new HashSet<chi_tiet_don_dat_hang>();
            this.chi_tiet_nhap_hang = new HashSet<chi_tiet_nhap_hang>();
            this.khoes = new HashSet<kho>();
        }
    
        public int stt { get; set; }
        public string id_xe { get; set; }
        public string ten_xe { get; set; }
        public string id_hang_xe { get; set; }
        public string id_loai_xe { get; set; }
        public short model_year { get; set; }
        public decimal gia_ban { get; set; }
        public byte bao_hanh { get; set; }
        public string mo_ta { get; set; }
        public decimal khuyen_mai { get; set; }
        public string id_nsx { get; set; }
        public bool is_con_hang { get; set; }
        public bool is_het_hang { get; set; }
        public bool is_khong_kinh_doanh { get; set; }
        public string anh_xe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_don_dat_hang> chi_tiet_don_dat_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_nhap_hang> chi_tiet_nhap_hang { get; set; }
        public virtual nsx nsx { get; set; }
        public virtual hang_xe hang_xe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kho> khoes { get; set; }
        public virtual loai_xe loai_xe { get; set; }
    }
}
